version: '3'

services: 
    server:
        build: ./barserver
        expose: 
            - 8080
     
        ports: 
            - 8080:8080
        volumes: 
            - ./barserver/src:/barproject/server/src
        command: npm run start

    client:
        build: ./reactui
        
        expose: 
            - 3001
        ports:
            - 3001:3001
       ## stdin_open: true
        volumes: 
            - ./reactui/src:/barproject/reactui/src
       ##     - ./reactui/public:/barproject/reactui/public
        links: 
            - server
        command: npm run expressstart