version: '3'

services: 
    server:
        build: ./barserver
        expose: 
            - 8080
        environment: 
            API_HOST: "http://localhost:3000/"
            APP_SERVER_PORT: 8080
        ports: 
            - 8080:8080
        volumes: 
            - ./barserver/src:/barproject/server/src
        command: npm run start

    client:
        build: ./reactui
        environment: 
            - REACT_APP_PORT=3000
        expose: 
            - 3000
        ports:
            - 3000:3000
        volumes: 
            - ./reactui/src:/barproject/reactui/src
            - ./reactui/public:/barproject/reactui/public
        links: 
            - server
        command: npm run start